---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: core.loc
  source:
    repoURL: https://github.com/YOUR_ORG/LocalLabRef.git
    path: kubernetes/apps/dashy
    targetRevision: main
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: dashy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
