---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - core-project.yaml
  - traefik-application.yaml
  - adguard-application.yaml
  - dashy-application.yaml
  - ollama-application.yaml
  - n8n-application.yaml
  - observability-application.yaml
