---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ollama-data
  namespace: ollama
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: storage
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ollama-models
  namespace: ollama
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: models
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 50Gi
