---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashy
  namespace: dashy
  labels:
    app.kubernetes.io/name: dashy
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: dashy.localhost.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashy
                port:
                  number: 8080
