---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dashy

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: dashy

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
