---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-adguard
  namespace: adguard
  labels:
    app.kubernetes.io/name: adguard
    app.kubernetes.io/component: storage
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
